### ISSUE TITLE
кринж

### ISSUE THREAD

**Issue by flexagoon** [Ultrageopro1966/my-site#1]
ты использовал `<button>` вместе с кодом `js` вместо простого `<a>` :-1:

**Comment by Ultrageopro1966** [comment]
сдохни тварь 

PS. Твоя мама ->
![image](https://user-images.githubusercontent.com/120571667/224269748-e1462ade-dc63-435f-9352-1342055ac90e.png)

**Comment by flexagoon** [comment]
![image](https://media.tenor.com/iCLR19N5OsMAAAAi/nooo.gif)
